// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBTdiWAjGe4GJpgfY6fGH2vC6iqCGcjZXk',
    appId: '1:139589833388:web:115ebdf4311514e458c509',
    messagingSenderId: '139589833388',
    projectId: 'instagram-da4b7',
    authDomain: 'instagram-da4b7.firebaseapp.com',
    storageBucket: 'instagram-da4b7.appspot.com',
    measurementId: 'G-85Z6548JD5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB8zfKNcfbJ17JpekUKhH70mJfAg-uf7PQ',
    appId: '1:139589833388:android:9db698a1d08fa19358c509',
    messagingSenderId: '139589833388',
    projectId: 'instagram-da4b7',
    storageBucket: 'instagram-da4b7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAjVTQ1x1rpMNE0bn88Xwzm4w_qKk0MnAc',
    appId: '1:139589833388:ios:2b2badc848ece6c258c509',
    messagingSenderId: '139589833388',
    projectId: 'instagram-da4b7',
    storageBucket: 'instagram-da4b7.appspot.com',
    iosBundleId: 'com.example.instagram',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAjVTQ1x1rpMNE0bn88Xwzm4w_qKk0MnAc',
    appId: '1:139589833388:ios:301a402ac68697e058c509',
    messagingSenderId: '139589833388',
    projectId: 'instagram-da4b7',
    storageBucket: 'instagram-da4b7.appspot.com',
    iosBundleId: 'com.example.instagram.RunnerTests',
  );
}
